name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/noun-search-5341750-use-1.png
    - assets/page-1/images/noun-arrow-2320225-blanc-1.png
    - assets/page-1/images/noun-media-1659860-magenta-1.png
    - assets/page-1/images/noun-history-4010676-blanc-1.png
    - assets/page-1/images/play-icone-personaliser-1.png
    - assets/page-1/images/noun-avatar-3793184-use-1.png
    - assets/page-1/images/arrow-right-blanc-1.png
    - assets/page-1/images/yao-1.png
    - assets/page-1/images/fichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-2.png
    - assets/page-1/images/tlchargement-1.png
    - assets/page-1/images/lusage-du-monde-21-1.png
    - assets/page-1/images/noun-search-5341750-use-1-cZf.png
    - assets/page-1/images/noun-media-1659860-magenta-2.png
    - assets/page-1/images/noun-tribal-4657083-jaune-2.png
    - assets/page-1/images/noun-wishlist-3027289-1.png
    - assets/page-1/images/noun-search-5341750-use-1-7g5.png
    - assets/page-1/images/loeil-du-cyclone-les-ex-enfants-soldats-des-bourreaux-comme-les-autres-1.png
    - assets/page-1/images/fichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-1.png
    - assets/page-1/images/djeli-1.png
    - assets/page-1/images/le-secret-de-chanda-1.png
    - assets/page-1/images/noun-avatar-3793184-use-1-uah.png
    - assets/page-1/images/revolution-africaine-thomas-sankara-1.png
    - assets/page-1/images/noun-history-4010676-blanc-1-SSu.png
    - assets/page-1/images/noun-tribal-4657083-jaune-1.png
    - assets/page-1/images/noun-feather-1914821-jaune-2.png
    - assets/page-1/images/noun-tribal-2584187-blanc-2.png
    - assets/page-1/images/noun-feather-1914821-jaune-4.png
    - assets/page-1/images/arrow-right-blanc-1-opM.png
    - assets/page-1/images/noun-play-1423160-blanc-1.png
    - assets/page-1/images/fespaco-2015-le-rendez-vous-du-cinma-africain-auletch-1.png
    - assets/page-1/images/play-icone-personaliser-1-NmX.png
    - assets/page-1/images/noun-avatar-3793184-use-1-Rsw.png
    - assets/page-1/images/play-icone-personaliser-1-K5K.png
    - assets/page-1/images/noun-tv-3962022-use-1.png
    - assets/page-1/images/arrow-right-blanc-2.png
    - assets/page-1/images/tlchargement-1-uhj.png
    - assets/page-1/images/noun-avatar-3793184-use-blanc-1.png
    - assets/page-1/images/noun-search-5347928-1.png
    - assets/page-1/images/play-icone-personaliser-1-H3w.png
    - assets/page-1/images/arrow-right-blanc-2-p3s.png
    - assets/page-1/images/noun-wishlist-3027289-1-Zn9.png
    - assets/page-1/images/fespaco-2015-le-rendez-vous-du-cinma-africain-auletch-1-a9o.png
    - assets/page-1/images/noun-tribal-2584187-blanc-2-Hpu.png
    - assets/page-1/images/ima-archives-des-dadju-lafrique-fait-son-cinema-1.png
    - assets/page-1/images/noun-avatar-3793184-use-2-bg.png
    - assets/page-1/images/arrow-right-blanc-2-D5j.png
    - assets/page-1/images/logo-log-1.png
    - assets/page-1/images/noun-share-1091662-blanc-1.png
    - assets/page-1/images/phpyhhumg-1.png
    - assets/page-1/images/djeli-1-egq.png
    - assets/page-1/images/noun-tribal-2584187-blanc-1.png
    - assets/page-1/images/noun-search-5341750-use-1-kzm.png
    - assets/page-1/images/back-top-options.png
    - assets/page-1/images/noun-history-4010676-blanc-1-wTP.png
    - assets/page-1/images/arrow-right-blanc-1-ech.png
    - assets/page-1/images/noun-search-5347928-1-aFT.png
    - assets/page-1/images/noun-tribal-4657083-jaune-2-XAh.png
    - assets/page-1/images/yao-1-GPB.png
    - assets/page-1/images/arrow-right-blanc-2-Pih.png
    - assets/page-1/images/arrow-right-blanc-2-Qpq.png
    - assets/page-1/images/images-1.png
    - assets/page-1/images/noun-feather-1914821-jaune-4-VLV.png
    - assets/page-1/images/noun-tv-3962022-use-1-nxq.png
    - assets/page-1/images/le-secret-de-chanda-1-KSy.png
    - assets/page-1/images/jours-a-sun-city-2-1.png
    - assets/page-1/images/noun-media-1659860-magenta-2-uJy.png
    - assets/page-1/images/arrow-right-blanc-1-Ec9.png
    - assets/page-1/images/noun-media-1659860-magenta-2-nNm.png
    - assets/page-1/images/arrow-right-blanc-2-GCh.png
    - assets/page-1/images/noun-feather-1914821-jaune-3.png
    - assets/page-1/images/noun-feather-1914821-jaune-3-miR.png
    - assets/page-1/images/loeil-du-cyclone-les-ex-enfants-soldats-des-bourreaux-comme-les-autres-1-545.png
    - assets/page-1/images/lascars-1.png
    - assets/page-1/images/images-1-mS1.png
    - assets/page-1/images/black-panther-bande-annonce-et-critique-1.png
    - assets/page-1/images/lusage-du-monde-21-1-Q4H.png
    - assets/page-1/images/noun-feather-1914821-jaune-1.png
    - assets/page-1/images/logo-log-1-8B3.png
    - assets/page-1/images/black-panther-bande-annonce-et-critique-2.png
    - assets/page-1/images/noun-tribal-4657083-jaune-2-JDw.png
    - assets/page-1/images/noun-avatar-3793184-use-1-krd.png
    - assets/page-1/images/jours-a-sun-city-2-2.png
    - assets/page-1/images/phpyhhumg-1-r4h.png
    - assets/page-1/images/black-panther-bande-annonce-et-critique-2-htD.png
    - assets/page-1/images/lascars-1-DLm.png
    - assets/page-1/images/play-icone-personaliser-1-WwK.png
    - assets/page-1/images/play-icone-personaliser-1-E6d.png
    - assets/page-1/images/play-icone-personaliser-1-EwT.png
    - assets/page-1/images/jours-a-sun-city-2-1-C9X.png
    - assets/page-1/images/ima-archives-des-dadju-lafrique-fait-son-cinema-1-dY5.png
    - assets/page-1/images/arrow-right-blanc-1-G2d.png
    - assets/page-1/images/noun-feather-1914821-jaune-4-Dof.png
    - assets/page-1/images/noun-feather-1914821-jaune-3-khX.png
    - assets/page-1/images/mfichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-1.png
    - assets/page-1/images/noun-feather-1914821-jaune-3-Xuj.png
    - assets/page-1/images/arrow-right-blanc-2-ToP.png
    - assets/page-1/images/noun-history-4010676-blanc-1-o8D.png
    - assets/page-1/images/wfichier-2rlb-ma000-444photo-final-rlb-on-yello-video-plus-1.png
    - assets/page-1/images/noun-tribal-2584187-blanc-2-1VB.png
    - assets/page-1/images/arrow-right-blanc-2-m3P.png
    - assets/page-1/images/amina-pokou-1.png
    - assets/page-1/images/jours-a-sun-city-2-2-B3P.png
    - assets/page-1/images/oifichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-2-bg.png
    - assets/page-1/images/bienvenue-en-afrique-film-2005-1.png
    - assets/page-1/images/jours-a-sun-city-3.png
    - assets/page-1/images/fichier-3rlb-ma000-444photo-final-rlb-on-yello-video-plus-1.png
    - assets/page-1/images/camille-cin-feuilles-1.png
    - assets/page-1/images/oifichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-1.png
    - assets/page-1/images/amina-pokou-1-m7P.png
    - assets/page-1/images/jours-a-sun-city-5.png
    - assets/page-1/images/logo-log-1-pgZ.png
    - assets/page-1/images/back-top-options-M7o.png
    - assets/page-1/images/oifichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-3-bg.png
    - assets/page-1/images/oifichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-3-bg-bHB.png
    - assets/page-1/images/noun-ok-3323824-bleu-2.png
    - assets/page-1/images/jours-a-sun-city-4.png
    - assets/page-1/images/jours-a-sun-city-5-rws.png
    - assets/page-1/images/djeli-1-Xvq.png
    - assets/page-1/images/arrow-right-blanc-1-QRw.png
    - assets/page-1/images/back-top-options-US5.png
    - assets/page-1/images/noun-search-5341750-use-1-UTb.png
    - assets/page-1/images/back-top-options-NQ9.png
    - assets/page-1/images/oifichier-1rlb-ma000-444photo-final-rlb-on-yello-video-plus-3-bg-zhf.png
    - assets/page-1/images/arrow-right-blanc-1-q8m.png
    - assets/page-1/images/back-top-options-xYy.png
    - assets/page-1/images/jours-a-sun-city-1.png
    - assets/page-1/images/jours-a-sun-city-3-3ny.png
    - assets/page-1/images/noun-search-5341750-use-1-Pi1.png
    - assets/page-1/images/djeli-1-FiZ.png
    - assets/page-1/images/logo-log-1-vad.png
    - assets/page-1/images/pexels-alexander-suhorucov-6457556-1.png
    - assets/page-1/images/jours-a-sun-city-1-AuP.png
    - assets/page-1/images/noun-about-3823859-blanc-1.png
    - assets/page-1/images/logo-log-2.png
    - assets/page-1/images/pexels-waldemar-brandt-3036332-1.png
    - assets/page-1/images/noun-star-5181959-gris-1.png
    - assets/page-1/images/jours-a-sun-city-4-Stq.png
    - assets/page-1/images/noun-wishlist-3027289-1-xcH.png
    - assets/page-1/images/noun-star-5181959-gris-1-Wxy.png
    - assets/page-1/images/pexels-charlotte-may-5965928-1.png
    - assets/page-1/images/noun-wishlist-3027289-1-AA5.png
    - assets/page-1/images/logo-log-1-Vy3.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-3.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-2.png
    - assets/page-1/images/noun-about-3823859-blanc-2.png
    - assets/page-1/images/noun-about-3823859-blanc-1-m8d.png
    - assets/page-1/images/djeli-2.png
    - assets/page-1/images/logo-log-1-FDs.png
    - assets/page-1/images/noun-help-1879360-blanc-1.png
    - assets/page-1/images/noun-avatar-3793184-use-1-Bcm.png
    - assets/page-1/images/noun-setting-1254362-blanc-1.png
    - assets/page-1/images/noun-option-3823535-bleu-blanc-1.png
    - assets/page-1/images/noun-search-5341750-use-1-XwX.png
    - assets/page-1/images/noun-edit-1432026-blanc-bleu-1.png
    - assets/page-1/images/noun-help-1879360-blanc-1-Y97.png
    - assets/page-1/images/noun-star-5181959-gris-1-98u.png
    - assets/page-1/images/noun-search-5341750-use-1-tMP.png
    - assets/page-1/images/noun-star-5181959-gris-1-Ew3.png
    - assets/page-1/images/arrow-right-blanc-1-zvD.png
    - assets/page-1/images/pexels-charlotte-may-5965928-2.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-2-uWH.png
    - assets/page-1/images/pexels-waldemar-brandt-3036332-1-CYR.png
    - assets/page-1/images/djeli-1-euF.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-1.png
    - assets/page-1/images/noun-star-5181959-gris-1-b7P.png
    - assets/page-1/images/djeli-1-cd7.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-1-xKT.png
    - assets/page-1/images/noun-tv-3962022-use-1-Ps7.png
    - assets/page-1/images/noun-about-3823859-blanc-3.png
    - assets/page-1/images/noun-search-5341750-use-1-Xds.png
    - assets/page-1/images/wfichier-2rlb-ma000-444photo-final-rlb-on-yello-video-plus-1-ARf.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-3-fNR.png
    - assets/page-1/images/wfichier-2rlb-ma000-444photo-final-rlb-on-yello-video-plus-2.png
    - assets/page-1/images/noun-arrow-right-1492413-blanc-4.png
    - assets/page-1/images/noun-setting-1254362-blanc-1-V5b.png
    - assets/page-1/images/noun-search-5347928-1-8k9.png
    - assets/page-1/images/noun-avatar-3793184-use-blanc-1-9pd.png
    - assets/page-1/images/pexels-bence-szemerey-7081182-1.png
    - assets/page-1/images/pexels-bence-szemerey-7081182-1-qKF.png
    - assets/page-1/images/pexels-alexander-suhorucov-6457556-2.png
    - assets/page-1/images/pexels-waldemar-brandt-3036332-1-sSh.png
    - assets/page-1/images/pexels-bence-szemerey-7081182-1-tMP.png
    - assets/page-1/images/pexels-bence-szemerey-7081182-1-zw3.png
    - assets/page-1/images/pexels-alexander-suhorucov-6457556-2-mFX.png
    - assets/page-1/images/pexels-waldemar-brandt-3036332-1-mds.png
    - assets/page-1/images/pexels-alexander-suhorucov-6457556-1-9RB.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
